services:
  localhost:
    container_name: postgres
    image: postgres:16.1
    environment:
      POSTGRES_DB: medicinemanagertest
      POSTGRES_USER: ahmed
      POSTGRES_PASSWORD: ahmedroot
      PGDATA: /data/postgres
    volumes:
      - localhost:/data/postgres
    ports:
      - "5330:5432"
    networks:
      - localhost
    restart: unless-stopped

networks:
  localhost:
    driver: bridge

volumes:
  localhost: