services:
  db:
    container_name: postgres
    image: postgres:16.1
    environment:
      POSTGRES_DB: medicinemanagertest
      POSTGRES_USER: ahmed
      POSTGRES_PASSWORD: ahmedroot
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5330:5432"
    networks:
      - db
    restart: unless-stopped
  prodDb:
    container_name: postgresProd
    image: postgres:16.1
    environment:
      POSTGRES_DB: medicinemanager
      POSTGRES_USER: ahmed
      POSTGRES_PASSWORD: ahmedroot
      PGDATA: /data/postgresProd
    volumes:
      - prodDb:/data/postgresProd
    ports:
      - "5331:5431"
    networks:
      - prodDb
    restart: unless-stopped

  medicinesmanager-api:
    container_name: medicinesmanager-api
    image: ahmedi999/medicinesmanager-api
    environment:
      -SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/medicinemanager

    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  medicinesmanager-react:
    container_name: medicinesmanager-react
    image: ahmedi999/medicinesmanager-react
    build:
      context: frontend/medicationmanagerreact
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - medicinesmanager-api
    restart: unless-stopped


networks:
  db:
    driver: bridge
  prodDb:
    driver: bridge

volumes:
  db:
  prodDb: