server:
  error:
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/medicinemanager
    username: postgres
    password: root

  mail:
    host: smtp.gmail.com
    port: 587
    username: medicationsmanager@gmail.com
    password: ucuu taeh vqey wjub

    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
    user: postgres
    password: root

authentication:
  header: Authorization
  type: Bearer
  jwt:
    issuer: Ahmed Ibrahim
    token-position-index: 7
    token-expiration: 1
  email:
    confirmationToken:
      expiresAt: 15

# cors and security-chain options should be seperated by ,
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
  registered-pattern: "/api/**"

security-chain:
  allowed-swagger-endpoints: /v3/api-docs,/v3/api-docs/**,/swagger-resources,/swagger-resources/**,/configuration/ui,/configuration/security,/swagger-ui/**,/webjars/**,/swagger-ui.html
  unauthenticated:
    post-endpoints: /api/v1/patients,/api/v1/auth/login,/api/v1/auth/send-verification
    get-endpoints:  /api/v1/auth/confirm



logging:
  level:
    org.flywaydb: trace

# Default value for picture url
medicine:
  picture-url: "https://i.imgur.com/qMA0qhd.png"


