name: CI - Build Backend
on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ahmedroot
          POSTGRES_DB: MedicineManagerTest
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Debug PostgreSQL Connection (Production)
        run: |
          apt-get update
          apt-get install -y postgresql-client
          psql -h localhost -U postgres -p 5432 -d MedicineManager -c 'SELECT 1;'
      - name: Debug PostgreSQL Connection (Test)
        run: |
          apt-get update
          apt-get install -y postgresql-client
          psql -h localhost -U postgres -p 5432 -d MedicineManagerTest -c 'SELECT 1;'   

      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify -Ddatabase.url=jdbc:postgresql://localhost:5332/MedicineManager -Ddatabase.username=postgres -Ddatabase.password=ahmedroot -Ddatabase.test.url=jdbc:postgresql://localhost:5332/MedicineManagerTest -Ddatabase.test.username=postgres -Ddatabase.test.password=ahmedroot