name: CI - Build Backend
on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ahmedroot
          POSTGRES_DB: MedicineManager
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Create Production Database
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          PGPASSWORD=ahmedroot psql -h localhost -U postgres -p 5332 -d MedicineManagerTest -W -c 'CREATE DATABASE "MedicineManagerTest";'
      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify