name: CI - Build Backend
on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ahmedroot
          POSTGRES_DB: medicinemanager,medicinemanagertest
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      #  DEBUGGING
      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '10s'

      - name: Collect Docker Logs
        uses: jwalton/gh-docker-logs@v1.0.0

      - name: Check running containers
        run: docker ps -a
      #  END OF DEBUG
      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify