name: CI - Build Backend

on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Database for production
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_USER: ahmed
          POSTGRES_PASSWORD: ahmedroot
          POSTGRES_DB: medicinemanager
        ports:
          - 5332
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      # Database for Integration tests
      postgresTest:
        image: postgres:16.1
        env:
          POSTGRES_USER: ahmed
          POSTGRES_PASSWORD: ahmedroot
          POSTGRES_DB: medicinemanagertest
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Initialize Database
        run: |
            sleep 10s
            psql -h localhost -U ahmed -d medicinemanagertest -a -f src/main/resources/db/migration/V1__initial_setup.sql

      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify